package com.ipz2014.android.model;

import com.github.nrudenko.orm.commons.DbType;
import com.github.nrudenko.orm.commons.Column;


/* AUTO-GENERATED FILE. CAREFUL TO MODIFY.
 *
 * This class was automatically generated by the
 * OrmGeneratorPlugin any changes will be overwritten
 * after next schema auto-generation
 */

public final class FeedbackPOJOScheme {

    public static final Column _ID = new Column("FeedbackPOJO._id",  DbType.INT); // PRIMARY AUTOINCREMENT
    public static final Column EMAIL = new Column("FeedbackPOJO.email",  DbType.TEXT);
    public static final Column FEEDBACK = new Column("FeedbackPOJO.feedback",  DbType.TEXT);

}